// <auto-generated />
using AwoBot.AudioCore.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AwoBot.AudioCore.EntityFramework.Migrations
{
    [DbContext(typeof(StoredTrackContext))]
    [Migration("20220828142952_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("AwoBot.AudioCore.EntityFramework.StoredTrack", b =>
                {
                    b.Property<string>("TrackId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiresDownload")
                        .HasColumnType("INTEGER");

                    b.HasKey("TrackId", "SourceId");

                    b.ToTable("StoredTracks");
                });
#pragma warning restore 612, 618
        }
    }
}
